project:
  type: website

website:
  title: "ğ‘“ğ‘"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yongrenjie
format:
  html:
    theme: litera
    css: styles.css
    mainfont: Fira Sans
    monofont: Fira Code
    linestretch: 1.7
    header-includes: |
      <link rel="preconnect" href="https://fonts.googleapis.com">
      <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
      <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@400;600&family=Fira+Sans:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet">
